language: csharp
dotnet: 3.1.201
mono: none
solution: TtxFromTS.sln

git:
  depth: false

script: dotnet build AudioCore/AudioCore.csproj --configuration Release 

jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11.3
    - os: windows