name: AudioCore Continuous Integration

on:
  push:
    branches: [ master ]
    paths:
    - 'AudioCore*/**'
  pull_request:
    branches: [ master ]

jobs:
  mac-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install AudioCore dependencies
      run: nuget restore AudioCore.csproj
      working-directory: ./AudioCore
    - name: Install AudioCore.Mac dependencies
      run: nuget restore AudioCore.Mac.csproj
      working-directory: ./AudioCore.Mac
    - name: Build library
      run: msbuild AudioCore.Mac.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release
      working-directory: ./AudioCore.Mac
    - name: Upload library artifact
      uses: actions/upload-artifact@v2
      with:
        name: AudioCore-Mac-Library
        path: AudioCore.Mac/bin/Release/
    - name: Install AudioCore.Demo.Mac dependencies
      run: nuget restore AudioCore.Demo.Mac.csproj
      working-directory: ./AudioCore.Demo.Mac
    - name: Build demo application
      run: msbuild AudioCore.Demo.Mac.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release
      working-directory: ./AudioCore.Demo.Mac
    - name: Copy demo app bundle to its own directory
      run: |
        mkdir bundle
        mv "AudioCore Demo.app" "bundle/AudioCore Demo.app"
      working-directory: ./AudioCore.Demo.Mac/bin/Release
    - name: Upload demo application artifact
      uses: actions/upload-artifact@v2
      with:
        name: AudioCore-Mac-Demo
        path: AudioCore.Demo.Mac/bin/Release/bundle/
