name: AudioCore Continuous Integration

on:
  push:
    branches: [ master ]
    paths:
    - 'AudioCore*/**'
  pull_request:
    branches: [ master ]

jobs:
  mac-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install AudioCore dependencies
      run: nuget restore AudioCore.csproj
      working-directory: ./AudioCore
    - name: Install AudioCore.Mac dependencies
      run: nuget restore AudioCore.Mac.csproj
      working-directory: ./AudioCore.Mac
    - name: Build
      run: msbuild AudioCore.Mac.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
      working-directory: ./AudioCore.Mac
